AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CloudFront AccessLogs Sample

Parameters:
  ApplicationName:
    Type: String
    Default: 'CloudFrontAccessLogsSample'

Resources:
  AccessLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: 30days
            Status: Enabled
            ExpirationInDays: 30
            NoncurrentVersionExpirationInDays: 30
    DeletionPolicy: Retain
  AccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AccessLogsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: SampleCloudFrontAccessLogsBucketRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub "arn:aws:s3:::${AccessLogsBucket}"
          - Sid: SampleCloudFrontAccessLogsBucketWrite
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:PutBucketAcl
            Resource: !Sub "arn:aws:s3:::${AccessLogsBucket}"

Outputs:
  BucketName:
    Description: "BucketName"
    Value: !Ref AccessLogsBucket
